### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#1307]
Hi, there! 👋 

Since I updated some CI workflows earlier this year, I've run into a few problems with things executing correctly and PRs are getting hung unnecessarily. I'm looking for someone familiar with GitHub Actions to get this working more reliably.

A couple PRs that are hung:
- #1305
- #1268

The [**Playwright**](https://github.com/codyogden/killedbygoogle/blob/main/.github/workflows/playwright.yml) workflow is the user interface testing and seems to be the one that gets hung. I need this workflow because Dependabot updates third-party user interface component packages, and this is my canary test that things are working as expected. It should run on all PRs _once a deployment preview is ready_, but seems to consistently fail when contributors open PRs with multiple commits.

**Comment by wxh06** [comment]
As I mentioned in https://github.com/codyogden/killedbygoogle/pull/1304#issuecomment-1272483311, I believe vercel bot, instead of Playwright, is the one that gets hung. Actually, the Playwright workflow has never been executed.

![Screen Shot 2022-10-20 at 15.14.03.png](https://user-images.githubusercontent.com/29367025/196881110-76c5f428-249c-4b95-89e5-2e88d73e682e.png)
