### ISSUE TITLE
Google Street View App

### ISSUE THREAD

**Issue by ChaseKnowlden** [codyogden/killedbygoogle#1316]
**What's the Product's Name?**
Google Street View App

**Describe the product in a single sentence.**
Google Street View App will be replaced by Google Maps in March 2023.

**When was the product launched? Provide a specific date, if possible.**
September 9, 2010

**When was the product discontinued? Provide a specific date, if possible.**
March 21, 2023

**What type of product was it? App, Service, or Hardware?**
App

**Comment by moom0o** [comment]
Can I leave my Google rant here?


They had a perfectly functioning Streetview app that would let you take near perfect 360 photos in AMAZING quality. These were called Photospheres and you could upload them to anywhere on google maps, now they're saying the app will stop working in 3 months and "everything is already on the Google Maps app". But if you go to the help page it says you have to use a 3rd party app in order to create them. Why the hell should I have to use an ad-ridden 3rd party app when there's a perfectly working one made by Google?? 
Furthermore, their new streetview studio only allows you to upload 360 videos, not photos. I've tried uploading some 360 drone pictures to Google maps like they said would work, but it only lets you upload them to a specific business and not a blue dot on the map (unless I can't find it.) AND the photo I uploaded wasn't even in 360!!!!  (even though it would've worked perfectly fine in the old app, it was the exact aspect ratio)
This is starting to piss me off, and I shouldn't have to resort to creating my own little program to upload photo spheres using their api, since I can't seem to properly upload them like I used to.

**Comment by pollocluck** [comment]
The Google Street View app is already unlisted on the App Store, but I don't understand why it isn't already listed on "the chopping block" for the KBG website. Here are some articles that the site can use as references:

https://www.theverge.com/2022/11/1/23435733/google-maps-street-view-standalone-app-discontinue-support
https://9to5google.com/2022/11/01/google-street-view-app-shutting-down/
