### ISSUE TITLE
Writely: renamed+rewritten, not killed?

### ISSUE THREAD

**Issue by mjulian** [codyogden/killedbygoogle#211]
I believe Writely evolved and wasn't killed off. It turned into Google Docs.

Source: https://softwareengineeringdaily.com/2017/12/15/high-volume-logging-with-steve-newman/

> In 2006, Writely was acquired by Google, and Steve spent his next four years turning Writely into Google Docs. - Steve Newman, co-founder of Writely

**Comment by codyogden** [comment]
Writely was acquired and replaced with Google Docs. It follows similar product acquisitions in the list like Meebo -> Google Talk/Chat, Sparrow -> Inbox, Grand Central -> Google Voice. I don't see any reason not to include it as a historical record of a product that Google has shut down.

**Comment by jsirois** [comment]
I'll also chime in on this one since I worked on the docs team from 2006-2008 with Steve, Sam and Claudia - but mostly with Steve. Writely was in no way killed. It was acquired and integrated into (really formed the basis of since the suite did not exist at the time) the docs suite, providing the word processor and the presentations app. The original Writely features only grew and improved - the Word Processor in docs today is a strict superset of Writely and as far as I can recall we migrated all Writely documents into google docs - ie no data was dropped. So the only thing that was killed was a brand name.
