### ISSUE TITLE
Include what apps were superseded by

### ISSUE THREAD

**Issue by kevinkace** [codyogden/killedbygoogle#322]
Eg. Writely was largely replaced with Docs.

**Comment by gooddadmike** [comment]
So something could certainly be added to gauge the impact of these killed projects. A body count for how many jobs were lost. How many users were disrupted. How many people still searching for an equivalent offering or settled for an inadequate replacement.

I will never forget you Google Reader!
How many innovations crushed?
Dodgeball comes to mind.
Also i wonder how many things Google mismanaged that were near-misses. Where another company has since succeeded. For instance Jaiku. Founded 1 month before Twitter.
Twitter is basically Jaiku-clone. In the same way that Oreos are a hydrox clone. So the copy-cat has a much better name and is just plain better, and the original is reduced to a footnote.

I know the related wiki articles may cover some of this but I'd like to see an indication of where things were acquired or innivated by Google that does live on in an open source or separate organization.

**Comment by flawyte** [comment]
I think it's a good idea. When you a look at this list it's easy to think "OMG Google why tho??" while actually some projects were simply replaced by others or were rewritten from the ground up with a new name. For example AngularJS is in the list, but the project itself isn't dead, it's just been replaced by a new version of the framework that was also rebaptized "Angular".

So maybe a simple text on a new line indicating "Not replaced" or "Replaced by XXX" could be a relevant info?
