### ISSUE TITLE
Add rumors

### ISSUE THREAD

**Issue by jango0** [codyogden/killedbygoogle#367]
There are a substantiated rumors that Google Play Music will be killed off and users will be pushed to Youtube Music. This has been reported by many tech sites.

This type of rumors would be an interesting addition to the website in my opinion.

**Comment by codyogden** [comment]
We're tracking Google Play Music in #350. All signs indicate Play Music will be killed in a few months. I would prefer not to be a speculative/rumor mill so that people can cite us confidently.

You can see the general workflow in #217 where we held off adding Hangouts to the list until a more official timeline was provided.
