### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by upintheairsheep** [codyogden/killedbygoogle#425]
Make an RSS feed.

**Comment by codyogden** [comment]
I think this is pretty easy to implement with a Node library. Since RSS is supposed to be a live feed, I would exclude pending product deaths.

What complicates this is that the graveyard data is generated during the build, so I'd need to trigger a rebuild once per day, which I don't think should be an issue. Hopefully it's as simple as a GitHub Action I can use to trigger Netlify to build.

**Comment by jrr** [comment]
Why would it need to run daily? It seems like an RSS feed need only update as frequently as the user-visible page does.

**Comment by upintheairsheep** [comment]
I don’t want this stale.

**Comment by upintheairsheep** [comment]
Ain’t stale!

**Comment by QuinnyPig** [comment]
https://github.community/t5/How-to-use-Git-and-GitHub/RSS-feeds-for-GitHub-projects/td-p/298 It already exists.

**Comment by somini** [comment]
This would be the second best thing / hack-y workaround:

https://github.com/codyogden/killedbygoogle/commits/master/graveyard.json.atom

**Comment by codyogden** [comment]
A feed is finally back on my roadmap and coming later this year. Closing for now. Thanks!

**Comment by dvikan** [comment]
@codyogden Hello! Is there any progress with the rss feed? Would love it.

**Comment by APT37** [comment]
7 years later, there still is no progress.

**Comment by GlitchyZorua** [comment]
I really wish we had this. Damn.
