### ISSUE TITLE
Add an "Imminent death" category

### ISSUE THREAD

**Issue by Secreto31126** [codyogden/killedbygoogle#616]
Sometimes, although Google doesn't announce the end of a service, it's obvious they will shut it down soon. It would be nice to see a pre-dedication for this apps or services.
Example, Play Music.

**Comment by codyogden** [comment]
I appreciate the suggestion!! 😄

I think it's best to avoid introducing speculation into the list and rather this be a source of factual, confirmed information. See my response in #367 and how we waited to add Hangouts in #217. Unlike other Google product cemeteries, we keep our list up-to-date and as accurate as possible. That's important because we're being cited as a resource **a lot**.

Regarding Play Music: Yeah. The writing has been on the wall since they killed the Artist Hub, and now that they've announced YouTube Music will be the default music player in the new Android version. It's just a matter of time until we get an official announcement from Google and then we'll be able to add it to the list!
