### ISSUE TITLE
Remove individual hardware products

### ISSUE THREAD

**Issue by satur9nine** [codyogden/killedbygoogle#673]
If a company ends a line of useful products then that would be noteworthy but saying that Google killed the Chromebook Pixel is not an accurate characterization given that individual pieces of hardware always go through a typical lifecycle that includes discontinuation. Google currently sells the Google Pixelbook (https://store.google.com/us/product/google_pixelbook) which is simply the next device in the product line. Would you say Apple killed the iPhone 4, iPhone 4S, iPhone 5, etc etc? No.

**Comment by Younes-L** [comment]
I disagree, there were 2 Chromebook pixels (2013 and 2015), and line of devices can consist of a single device.
The names are also clearly different.
It's more like a pixel phone to a nexus phone (even the pixel C is in a category of it's own, originally chromebook, named a pixel, treated as a nexus...)

**Comment by satur9nine** [comment]
Chromebook Pixel vs Pixelbook is merely rebranding. Nexus products were not co-branded with their original OEM and the original OEM had a much larger say in the design and development than Pixel phones. If you count rebranding as "killed" then you should really specify it was the brand that was killed and not the product. No matter how you slice it, it makes no sense to list specs like RAM, processor, screen size and then say it was killed. No one expects any hardware company to continue producing the same spec device indefinitely.

**Comment by codyogden** [comment]
> Would you say Apple killed the iPhone 4, iPhone 4S, iPhone 5, etc etc? No.

We kind of hashed out the pattern for this situation in #221. We decided to consolidate similarly branded hardware devices (phones & tablets) under Nexus with a couple exceptions: for the Nexus Player and Nexus Q, we left separate entries. We'll do the same for "Google Pixel" when they kill the brand in the future and leave separate entries for outlier devices.

For example, following that pattern, we won't add individual Pixel phones (Pixel, Pixel 2, Pixel 3, Pixel 3a, Pixel 4, etc) or the Pixel Slate tablets until the branding is eventually dropped, and then simply call it "Google Pixel." That leaves devices like Chromebook Pixel and Google Pixelbook deserving of separate entries. I'll concede that these products share mutated branding, but they are notable, separate products that function well outside the flagship Pixel branding.

> Chromebook Pixel vs Pixelbook is merely rebranding. 

I think it is easy to draw that conclusion, but the timeline doesn't really support it. Chromebook Pixel was released in 2013 and Chromebook Pixel 2 in 2015. The line was discontinued in 2016 before a [successor had even been announced](https://venturebeat.com/2016/08/29/chromebook-pixel-2-discontinued/). Google Pixelbook wouldn't be announced until [over a year after Chromebook Pixel was discontinued](https://techcrunch.com/2017/10/26/google-pixelbook-review-the-chromebook-grows-up/). This is a bit of a departure from traditional hardware product lifecycle that you've mentioned and exemplified with other manufacturers where a successor is generally announced before sales and manufacturing of the original device are ceased. Chromebook Pixel was also a notable product at the time since it was Google's first attempt at a laptop computer.

> it makes no sense to list specs like RAM, processor, screen size and then say it was killed

I agree with your issue with the description. It's overly technical, and it doesn't fit in with the other entries nor meet the quality I expect to have on Killed by Google. It seems like the description needs a bit of a refresh to make it more palatable.

Overall, I don't feel it isn't disingenuous or misleading to include Chromebook Pixel separately. It was not a primary device brand (Pixel phone or tablet), it did not have a publicly announced successor after it was discontinued, it is a notable 'first of its kind' product, and the branding diverged from the primary line when the new successor was announced.

- [ ] Update the Chromebook Pixel description.
