### ISSUE TITLE
[discuss] Mb add "lib" category?

### ISSUE THREAD

**Issue by thaelathy** [codyogden/killedbygoogle#694]
Angular JS is not quite and app, it's a framwork to make an app. Also, Polymer is not an app, but there's no category to fit those things well.

**Comment by mskadu** [comment]
My vote: **Yes**

If I am reading the title right (mb <--> maybe?), the suggestion is to add "library" (or something on the lines - maybe _component_?) as a possible value to the `type` param. It does make sense since Google does tend to release (and eventually kill) reusable components, libraries, etc. And they don't exactly fit under the "app" type.

Suggested next step: Short term - Use _app_ as a short term value for `type`. Long term - TBD.

**Comment by codyogden** [comment]
I'm thinking through a lot of issues right now. Specifically addressing lower-level tech items like AngularJS and some other pending and added items. I'll add a label to this to come back to it in a bit.
