### ISSUE TITLE
Show whether the app/service was just an experiment, not a big investment or merged into other products

### ISSUE THREAD

**Issue by googleooer** [codyogden/killedbygoogle#810]
so users realize most dead services/apps were just experiments or integrated into/replaced by other products

**Comment by funnel20** [comment]
This is an excellent idea. I visited your website for the first time today. While scrolling I recognized several services that are deprecated (such as Fabric and GCM), because they were merged into the Firebase service. 
So technically they are not dead, but continue to live under a new name. So maybe an extra property to each project can hold this information, e.g. “superseded by”.

**Comment by funnel20** [comment]
Hi @codyogden , can you elaborate why this issue is closed? Has it been implemented, is it just a stupid idea, or something else? Based on the thumbs ups there seems to be a demand for this.

**Comment by codyogden** [comment]
@funnel20 Sorry. I thought I added a comment. Since this project doesn't use a database and I don't see a reason to add one in the foreseeable future, I'm noting any enhancement requests into a backlog and closing issues. Apologies for the missing comment.

**Comment by funnel20** [comment]
@codyogden That makes perfect sense. Thanks for moving it into a backlog.
