### ISSUE TITLE
Google Hangouts entry is wrong/Support unknown close dates

### ISSUE THREAD

**Issue by RonAmadeo** [codyogden/killedbygoogle#957]
Hi. Big fan. Currently, the Google Hangouts entry says the app is dying in 7 days. This is not true. We have no idea when Google Hangouts is closing. (The current date is a reference to Google Chat launching, which happened last week.)

I was going to try and fix this myself, but it looks like an exact close date is mandatory? I'm assuming "dateClose" can't handle a question mark or blank spaces.

If you're going to list future shutdowns, ideally an unknown close date would be supported rather than making up a random date in the future. Hangouts is not the first time this has happened. Allo was also announced as "[Paused](https://arstechnica.com/gadgets/2018/04/google-gives-up-on-google-allo-hopes-carriers-will-sort-out-rcs-messaging/)" without a firm close date initially.

**Comment by codyogden** [comment]
Hi, Ron. :)

You're correct that Hangouts hasn't closed yet, and we don't know when it will be shut down. Generally, these have come from announcements from Google indicating "late 2020" or "mid-2021."

Since we don't have a way to earmark things as "dying," I'm in favor of just removing the entry. Thoughts?

**Comment by RonAmadeo** [comment]
Sure that works. It'll be back.
